### PR TITLE
FIFO buffered data extraction

### PR DESCRIPTION
**Pull request by rvanee**
This is a major update to the library, allowing for FIFO buffered reading of data from the LSM6DSOX at various sample rates. On I2C a maximum of 1667/s can be obtained using I2C (Arduino Nano RP2040 Connect).

### CODE REVIEW

**Comment by rvanee** [comment]
I hope you find this update useful. It hasn't been an easy journey towards this code.

**Comment by rvanee** [comment]
I notice that not much seems to be happening. Is there anything I can assist you with?

**Comment by facchinm** [comment]
Hi @rvanee ,
I'm sorry but PRs like this are close to impossible to merge or review properly.
Cleaning up the branch and providing a series of [atomic](https://www.aleksandrhovhannisyan.com/blog/atomic-git-commits/) patches with clear scope (like "Add FIFO support" or "Add BLE example" ) would help that process.
I'll give you some guidance if needed :slightly_smiling_face:

**Comment by rvanee** [comment]
I received a request to make atomic patches.

**Comment by per1234** [comment]
Hi @rvanee. You are welcome to make the requested changes to this PR by [force pushing](https://git-scm.com/docs/git-push#Documentation/git-push.txt---no-force-with-lease) to the branch in your fork.

Or if you prefer, you can open a new PR.

**Pull request closed without merging**
